{"version":1,"defects":{"Tests\\Unit\\RouterTest::it_registers_a_route":4,"Tests\\Unit\\RouterTest::it_registers_post_route":3,"Tests\\Unit\\RouterTest::test_no_routes_when_router_created":4,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #3":3,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #2":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":3,"Tests\\Unit\\RouterTest::is_recolved_route_from_a_clouser":3,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":3},"times":{"Tests\\Unit\\RouterTest::it_registers_a_route":0.002,"Tests\\Unit\\RouterTest::test_it_registers_a_route":0.001,"Tests\\Unit\\RouterTest::it_registers_get_route":0,"Tests\\Unit\\RouterTest::it_registers_post_route":0,"Tests\\Unit\\RouterTest::test_no_routes_when_router_created":0,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #0":0.001,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::test_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::is_recolved_route_from_a_clouser":0,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":0.003}}